name: Register APP

on:
  schedule:
    - cron: "0 3 */1 * *"
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Requirements
        run: |
          poetry install
          cd register
          npm install

      - name: Register App
        env:
          USER: ${{ secrets.USER }}
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          cd register
          bash register_apps_by_force.sh
          cd ..
          poetry run python crypto.py e

      - name: Commit And Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          bash reset.sh "Generate App Config"
          git config --unset-all http.https://github.com/.extraheader || true
          git remote set-url origin "https://prism-w:${GH_PAT}@github.com/prism-w/KeepAliveE5.git"
          git push -f origin master 2>&1